### ISSUE TITLE
Fix the colored squares in the lessons in the `modules` repo

### ISSUE THREAD

**Issue by dmil** [code4policy/2022#14]
The image is missing

https://github.com/code4policy/modules/blob/master/agile/03-user-stories.md#-try-it

That used to be a colored square in the color of the hex code listed there (in that case `#f03c15 `). Seems like this broke across the board. Let's find a way to fix that.

**Comment by pcsong33** [comment]
colored squares fixed with the following new emojis:
➡️ Try It
❇️ Example
🔶 Pop Quiz

**Comment by dmil** [comment]
Thanks!
