### ISSUE TITLE
Issue downloading Python on Mac

### ISSUE THREAD

**Issue by kelseylandau1** [code4policy/2022#19]
I'm unable to use "brew install python" to download Python on my Mac computer, perhaps due to having an older (Mojave) operating system. However, I'm also unable to download a newer operating system--it says that I need 12 gb on my computer to download, which I have, and it lets me start downloading from there; however, once the 12gb is downloaded and the installer launches, it says I need another 30gb of space on top of that, which I don't have. ![Screen Shot 2022-01-04 at 9 47 43 AM](https://user-images.githubusercontent.com/60553728/148077621-d99f5956-0ecc-4c7c-a8ed-1c1892babaa8.png) (The 12gb download also seems to be taking up valuable storage space on my computer, which is irritating but a less severe issue.)

Here is the specific the error message on Terminal I get when I run the "brew install python" command. I've now downloaded the "Command Line Tools for Xcode 11.3.1" package twice to try to fix the issue per the suggestion, but it doesn't seem to recognize that I've done so and keeps giving me the error message regardless. 
![Screen Shot 2022-01-04 at 9 47 27 AM](https://user-images.githubusercontent.com/60553728/148077680-fd010edf-8141-47c5-857e-783af883a741.png)

I'm not sure whether I need to update the operating system to fix this problem (or whether I need to for the class in general), or whether there's another fix to the "Command Line Tools" error--any guidance much appreciated!

**Comment by pcsong33** [comment]
Hi Kelsey, before reinstalling Command Line Tools, have you tried running the command:
sudo rm -rf /Library/Developer/CommandLineTools
in your terminal? And if you have, what is the output you get from running that command?

**Comment by kelseylandau1** [comment]
Hey Patrick! So, strangely enough, the first time I ran that line of code (a few days ago), nothing happened, but I just closed Terminal and ran it all again, and seem to have made more progress than before? I can't quite tell what this code means, but it is further than I've gotten in the past so maybe that's some kind of progress :)

![Screen Shot 2022-01-04 at 3 10 15 PM](https://user-images.githubusercontent.com/60553728/148117929-9a295f82-9aea-4cac-a78d-8779b4346728.png)

Any chance you're able to interpret?

**Comment by pcsong33** [comment]
from this screenshot, it seems like the command is still running, did you end up getting to an output message or did the command execute to the point where you were able to see the:
Kelseys-MacBook-Air: ~kelseylandau$
prompt again?

**Comment by pcsong33** [comment]
Also, I am on gather.town for office hours right now, happy to troubleshoot with you together there if you keep running into issues.

**Comment by kelseylandau1** [comment]
Wait you're right, looks like it worked!

![Screen Shot 2022-01-04 at 3 36 14 PM](https://user-images.githubusercontent.com/60553728/148120786-29a97494-dfb7-4051-abb6-890d5b92a4b9.png)

Not really sure why it worked this time and not previously, but can't complain! So unless you think otherwise, I think this issue may be resolved?

**Comment by pcsong33** [comment]
Awesome! Looks good to me, let me know if you continue to run into any additional errors.
