### ISSUE TITLE
Setup code4policy slack

### ISSUE THREAD

**Issue by dmil** [code4policy/2022#3]
Currently, we have code4policy.slack.com, but I've been making a new one each year (e.g. code4policy2021.slack.com). Ideally, I'd like for this to be a lasting community that includes alumni. But the original code4policy slack is a bit too messy to re-use. Can we purge it of all channels and users and start over and create some kind of schema for using the same slack each year? 

Alternatively, just setup code4policy2022 slack and close this issue!

**Comment by dmil** [comment]
Also, just a note that I grade participation with https://github.com/code4policy/slackvisualizer

So, one issue with reviving the old channel may be that if we're past the free tier, it starts to delete messages. So when we go back to grade participation, messages start to vanish. So we'll have to make sure that doesn't happen, or find a different way to grade participation.

I suppose we could try the "Discussion" tab in GitHub, but I prefer to just allow students to interact organically on Slack and just grade that.

**Comment by dmil** [comment]
- @pcsong33 look into the immediate issue for the class
- @traghuram look into long-term community building

**Comment by pcsong33** [comment]
On the immediate issue front, I believe that re-using the old code4policy workspace should still be viable. Slack saves the most recent 10,000 messages, so I believe that the visualizer should still be able to show participation statistics for the duration of the class. The previous code4policy workspace used less than 6,000 messages.

**Comment by pcsong33** [comment]
I did try to run the slackvisualizer locally, but I ran into an issue where it seems as though the API key setup for the slack app seems to be [deprecated](https://api.slack.com/legacy/custom-integrations/legacy-tokens). @dmil It would be great if you could check on your end if the slack participation visualizer app still works on your end, and if not, we can maybe attempt to update the app.

**Comment by dmil** [comment]
Ah, @pcsong33 we may need to update the app. No rush on that, but we should do it by the end of class. We also need to pay attention to the retention policy to make sure it will retain the messages and allow us to access them via the api. Either i'll have to pay to upgrade the slack or we should switch over to a new one like `code4policy2022`.

**Comment by dmil** [comment]
Resolved, we decided to stick to `code4policy`. We will pay for the premium plan ($8/month) if we start to notice messages disappearing.

**Comment by dmil** [comment]
@pcsong33 - whenever you have a minute, can you try this?
https://github.com/kfei/slack-cleaner

It should help us further clean up the channels (remove all the files and empty out #general). If it works, it's a nice scripted way to "reset" for next year when the class ends.

**Comment by pcsong33** [comment]
general channel has been cleaned! and old channels and files have been deleted.

**Comment by dmil** [comment]
🙌 ... Thanks!
