### ISSUE TITLE
Decide on Ticketing System

### ISSUE THREAD

**Issue by dmil** [code4policy/2022#4]
Should we use this ticketing system with students, or just stick to slack?

**Comment by pcsong33** [comment]
Github + Slack Integration channel has been setup!

**Comment by dmil** [comment]
great, thanks! 

@pcsong33 @traghuram - if either of you can think of improvements to the default tickets, let me know, or just file a PR

Here are the current templates:
https://github.com/code4policy/2022/issues/new/choose

Ticket templates can be edited or added here:
https://github.com/code4policy/2022/tree/main/.github/ISSUE_TEMPLATE
