### ISSUE TITLE
Decide on office hours

### ISSUE THREAD

**Issue by dmil** [code4policy/2022#8]
Edit office hours slide here:
https://slides.com/dhrumilmehta/numbers-to-narrative/edit

to reflect what we decide

**Comment by pcsong33** [comment]
I don't seem to have edit access (or view access) to the slides.

**Comment by dmil** [comment]
patrick, morning - taran afternoon

**Comment by dmil** [comment]
https://slides.com/dhrumilmehta/hks-intro/edit

**Comment by traghuram** [comment]
To confirm, it's @traghuram morning and @pcsong33 afternoon.

Also, I can take office hours from 9-10am and 2-3pm, and I'll be available on slack otherwise.

**Comment by pcsong33** [comment]
I should be able to take office hours from 12-2 pm!

**Comment by dmil** [comment]
Hmm...I'll say tentatively this is okay, but we may want to shift them around later if we get a lot of requests during the evening. 

Also, let's try to spare some 10 minutes for a quick teaching team standup between the two classes daily. I'll say tentatively 2pm-ish, but if students need a little help after class with anything it may be a little later.

**Comment by traghuram** [comment]
How about I just take 6-8pm for OH instead? Totally fine to do that
