### ISSUE TITLE
Update roster in User Stories slides

### ISSUE THREAD

**Issue by dmil** [code4policy/2022#9]
For sections A and B, please update the roster for user stories. I will share the link via slack since this is a public forum at the moment.

**Comment by dmil** [comment]
let's just update names and if it is not too annoying, photos

**Comment by pcsong33** [comment]
created a section b presentation in the drive

**Comment by traghuram** [comment]
Updated section A with names only from roster (not pictures)

**Comment by dmil** [comment]
Thanks, you should have pictures once you get access to my.harvard
